export const ChartJson = [
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
  {
    isActive: true,
    mobility: 0,
    implant: false,
    furcation: "",
    pockerdepth: [0, 0, 0],
    recession: [0, 0, 0],
    bleeding: ["grey", "grey", "grey"],
    plaque: [false, false, false],
    p_furcation: ["", ""],
    p_pockerdepth: [0, 0, 0],
    p_recession: [0, 0, 0],
    p_bleeding: ["grey", "grey", "grey"],
    p_plaque: [false, false, false],
  },
];
